auth.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import login_user, login_required, logout_user, current_user

import os
import psycopg2

auth = Blueprint('auth', __name__)


# Get connection to the PostgreSQL DB
os.environ['DB_USERNAME'] = 'admin'
os.environ['DB_PASSWORD'] = 'PurplePine015'
def connect_db():
    con = psycopg2.connect(host='localhost',
                            database='book_db',
                            user=os.environ['DB_USERNAME'],
                            password=os.environ['DB_PASSWORD'])
    return con

@auth.route('/sign-up', methods=['GET', 'POST'])
def sign_up():
    if request.method == 'POST':
        email = request.form.get('email')
        user_name = request.form.get('firstName')
        password1 = request.form.get('password1')
        password2 = request.form.get('password2')

        # TODO: GO Through all the emails on user table and check that the email does not exist
        """
            CURRENT ERROR if EMAIL is Duplicated
            psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "users_email_key"
            DETAIL:  Key (email)=(lillo@gmail.com) already exists.
        """
        user = False
        if user:
            flash('Email already exists.', category='error')
        elif len(email) < 4:
            flash('Email must be greater than 3 characters.', category='error')
        elif len(user_name) < 2:
            flash('User name must be greater than 1 character.', category='error')
        elif password1 != password2:
            flash('Passwords don\'t match.', category='error')
        elif len(password1) < 7:
            flash('Password must be at least 7 characters.', category='error')
        else:
            
            conection = connect_db()
            cursor = conection.cursor()
            cursor.execute('INSERT INTO users (email, password, user_name)'
                    'VALUES (%s, %s, %s)',
                    (email, password1, user_name))
            conection.commit()
            cursor.close()
            conection.close()
            
            
            flash('Account created!', category='success')
            return redirect(url_for('views.home'))

    return render_template("sign_up.html", user=current_user)

views.py
"""
    Author: Lute Lillo Portero
    lute47lillo
"""
import os
import psycopg2
from flask import Flask, render_template, request, jsonify, url_for, flash, redirect
from flask import Blueprint

# Create a blueprint of init app (Easier way to divide the project)
views = Blueprint('views', __name__)

# Set variable environment for the database
# TODO: Make them private
os.environ['DB_USERNAME'] = 'admin'
os.environ['DB_PASSWORD'] = 'PurplePine015'

#ACTIVATE BELOW FOR REC SYSTEM Create functions for requesting the data needed
#from recommendation_model import get_predictions

# Get connection to the PostgreSQL DB
def connect_db():
    con = psycopg2.connect(host='localhost',
                            database='book_db',
                            user=os.environ['DB_USERNAME'],
                            password=os.environ['DB_PASSWORD'])
    return con


# Page to render the base.html file from template dir HOMEPAGE
@views.get("/")
def index_get():
    return render_template("index.html")

@views.route('/')
def home():
    return render_template('index.html')

'''
    1. Call DB connection and fetch all data into the web browser
    2. If remove is called, delete the entry for which id is matched
'''
@views.route('/book_thought/',methods=('GET', 'POST'))
def book_thought():
    
    # Set-UP connections
    conect = connect_db()
    cursor = conect.cursor()
    
    if 'remove' in request.form:
        book_id = int(request.form['index'])
        print(book_id)
      
        cursor.execute("DELETE FROM books WHERE book_id='%s'"  % book_id)
        conect.commit()
        cursor.close()
        conect.close()
        return redirect(url_for('views.book_thought'))
    
    # Execute commands to retrieve
    cursor.execute('SELECT * FROM books;')
    books = cursor.fetchall()
    
    # Disconect
    cursor.close()
    conect.close()
    
    return render_template('book_thought.html', books=books)


@views.route('/book_recommendation/')
def book_recommendation():
    return render_template('book_rec.html')

'''
    Create a new entry review/thought idea into the DB
    TODO: retrieve the user connected in that moment and save it to that user.
'''
@views.route('/review/', methods=('GET', 'POST'))
def review():
    
    if request.method == 'POST':
        title = request.form['title']
        author = request.form['author']
        quotes = request.form['quotes']
        review = request.form['review']
        print(title)

        conection = connect_db()
        cursor = conection.cursor()
        cursor.execute('INSERT INTO books (title, author, quotes, review)'
                    'VALUES (%s, %s, %s, %s)',
                    (title, author, quotes, review))
        conection.commit()
        cursor.close()
        conection.close()
        return redirect(url_for('views.book_thought'))
        
    return render_template('book_review.html')

"""
    1. From book_thought.html we select X book to be edited, 
    then index is requested and form is loaded with previous
    data.
    2. Save changes button is pressed and changes are saved
    to the DB
    #TODO: When editing, the order of the databse changes showing the updated element last
    MAYBE UPDATE THE DATE ADDED TO BE UPDATEED

"""
last_access_id = []
@views.route('/edit/', methods=['GET', 'POST'])
def edit():

    if request.method == 'POST':
        
        # Load previous data of X book
        if 'index' in request.form:
            # do things
            book_id = int(request.form['index'])
            last_access_id.append(book_id)
        
            # Set-UP connections
            conect = connect_db()
            cursor = conect.cursor()
    
            # Execute commands to retrieve
            cursor.execute("SELECT * FROM books WHERE book_id='%s'"  % book_id)
            books = cursor.fetchall()

            # Disconect
            cursor.close()
            conect.close()
    
            return render_template('edit_thought.html', books=books)
        
        else:
            # Save changes button to load new data into the DB.
            title = request.form['title']
            author = request.form['author']
            quotes = request.form['quotes']
            review = request.form['review']
            print(title)

            conection = connect_db()
            cursor = conection.cursor()
            
            
            # Create SQL Query
            sql = """   UPDATE books
                        SET title = %s, author = %s, quotes= %s, review=%s
                        WHERE book_id = %s;
                  """
            # Since you cannot access the edit page unless you selected a book_id by editing
            # the last access will always be the one on edition.
            # TODO: Maybe when deleting -> Remember to delete the list
            cursor.execute(sql, (title, author, quotes, review, last_access_id[-1]))
                    
            conection.commit()
            cursor.close()
            conection.close()
            
            return redirect(url_for('views.book_thought'))
        
    return render_template('book_thought.html')

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">

    <meta charset="UTF-8">
    <title>{% block title %} {% endblock %} - Haul Of Thoughts</title>
    <!-- .alert -> Create an alert message when some part of the review (title or content is missing)-->
    <style>
        nav a {
            color: #d64161;
            font-size: 3em;
            margin-left: 50px;
            text-decoration: none;
        }

        .book {
            padding: 20px;
            margin: 10px;
            background-color: #f7f4f4;
        }
    
        .review {
            margin-left: 50px;
            font-size: 20px;
        }
        
    </style>
</head>
<body>
    <nav>
        <!-- Passing the name of the view function created by the decorator at app.py 
             Therefore, routes can be edited without being break.
        -->
        <a href="{{ url_for('views.home')}}">Home</a>
        <a href="{{ url_for('views.book_recommendation') }}">Book Recommendation</a>
        <a href="{{ url_for('views.book_thought') }}">Book Thought</a>
        <a href="{{ url_for('auth.sign_up') }}">Sign Up</a>
    </nav>
    {% with messages = get_flashed_messages(with_categories=true) %} 
    {% if messages %} 
    {% for category, message in messages %} 
    {% if category == 'error' %}
        <div class="alert alert-danger alter-dismissable fade show" role="alert">
          {{ message }}
        </div>
        {% else %}
        <div class="alert alert-success alter-dismissable fade show" role="alert">
          {{ message }}
        </div>
        {% endif %} {% endfor %} {% endif %} {% endwith %}
    <hr>
    {% block content %} {% endblock %}
    <!-- Optional JavaScript -->

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj" crossorigin="anonymous"></script>

</body>
</html>

templates/book_rec.html
{% extends 'base.html' %}

<!-- Extends gets the base content from the base.html
    block contents are derived and declared on the base.html file too
    The code below is original to the page that uses index.html
-->
{% block content %}
    <h1>{% block title %} Book Recommendation {% endblock %}</h1> 
    <h2>Here you will be able to get a book recommendation</h2>
    <body>
        It will be able thanks to a recommendation system made of a KNN model using the goodreads dataset.
    </body>
{% endblock %}

templates/book_review.html
{% extends 'base.html' %}

{% block content %}
    <h1>{% block title %} Add a New Book {% endblock %}</h1>
    <form method="post">
        <p>
            <label for="title">Title</label>
            <input type="text" name="title"
                   placeholder="Book title">
            </input>
        </p>

        <p>
            <label for="author">Author</label>
            <input type="text" name="author"
                   placeholder="Book author">
            </input>
        </p>

        <p>
            <label for="quotes">Interesting Quotes</label>
            <br>
            <textarea name="quotes" placeholder="Quotes" rows="10" cols="60"></textarea>
            </p>

        <p>
            
        <label for="review">Review</label>
        <br>
        <textarea name="review" placeholder="Review" rows="20" cols="60"></textarea>
        </p>
        <p>
            <button type="submit">Submit</button>
        </p>
    </form>
{% endblock %}

templates/book_thought.html
{% extends 'base.html' %}

<!-- Extends gets the base content from the base.html
    block contents are derived and declared on the base.html file too
    The code below is original to the page that uses index.html
-->
{% block content %}
    <h1>{% block title %} Book Thoughts {% endblock %}</h1> 
    <!-- Using Jinja logic engine -->
    {% for book in books %}
    <div class='book'>
        <h3>#{{ book[0] }} - {{ book[2] }} by {{ book[3] }}</h3>
        <i><p>INSPIRING QUOTES:<br>
            {{ book[4] }} </p></i>
        <p class='review'>{{ book[5] }}</p>

        <!-- Form to send data to Falsk backend. Send book-id for loading and edit -->
        <form action="/edit" method="post" role="form">
            <input type="hidden" id="index" name="index" value="{{ book[0] }}">
            <a href="{{ url_for('views.edit') }}" target="_parent"><button type="submit" name="index" value="edit">Edit</button></a>
        </form>
        <form method="post" role="form">
            <input type="hidden" id="index" name="index" value="{{ book[0] }}">
            <button type="submit" name="remove" value="remove">Remove</button>
        </form>

    </div>
    {% endfor %}
    
    <div>
        <a href="{{ url_for('views.review') }}" target="_parent"><button type="submit">Review new book</button></a>
    </div>
{% endblock %}

templates/edit_thought.html
{% extends 'base.html' %}

{% block content %}
    <h1>{% block title %} EDIT Book Thoughts {% endblock %}</h1> 
    <!-- Using Jinja logic engine -->
    {% set books = books %}
    <form method="post">
        <p>
            <label for="title">Title</label>
            <input type="text" name="title" value="{{books[0][2]}}"></input>
        </p>

        <p>
            <label for="author">Author</label>
            <input type="text" name="author"value="{{books[0][3]}}"></input>
        </p>

        <p>
            <label for="quotes">Interesting Quotes</label>
            <br>
                <textarea name="quotes" rows="10" cols="60">{{books[0][4]}}</textarea>
        </p>

        <p>   
            <label for="review">Review</label>
            <br>
                <textarea name="review" rows="20" cols="60">{{books[0][5]}}</textarea>
        </p>

        <p>
            <a href="{{ url_for('views.review') }}" target="_parent"><button name="edit_btn" type="submit">Save changes</button></a>
        </p>
    </form>
{% endblock %}

templates/index.html
{% extends 'base.html' %}

<!-- Extends gets the base content from the base.html
    block contents are derived and declared on the base.html file too
    The code below is original to the page that uses index.html
-->
{% block content %}
    <h1>{% block title %} Home {% endblock %}</h1> 
{% endblock %}

templates/sign_up.html
{% extends "base.html" %} {% block title %}Sign Up{% endblock %} {% block
    content %}
    <form method="POST">
      <h3 align="center">Sign Up</h3>
      <div class="form-group">
        <label for="email">Email Address</label>
        <input
          type="email"
          class="form-control"
          id="email"
          name="email"
          placeholder="Enter email"
        />
      </div>
      <div class="form-group">
        <label for="firstName">First Name</label>
        <input
          type="text"
          class="form-control"
          id="firstName"
          name="firstName"
          placeholder="Enter first name"
        />
      </div>
      <div class="form-group">
        <label for="password1">Password</label>
        <input
          type="password"
          class="form-control"
          id="password1"
          name="password1"
          placeholder="Enter password"
        />
      </div>
      <div class="form-group">
        <label for="password2">Password (Confirm)</label>
        <input
          type="password"
          class="form-control"
          id="password2"
          name="password2"
          placeholder="Confirm password"
        />
      </div>
      <br />
      <button type="submit" class="btn btn-primary">Submit</button>
    </form>
    {% endblock %}